language: bash
services: docker
before_install:
  - cd rest-with-spring-boot-udemy/
  - echo "We are in the Docker folder"
script: 
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker image push 'gsabbara/mysql-rest-with-spring-boot-udemy:latest'
    docker image push 'gsabbara/rest-with-spring-boot-udemy:latest'
  on:
    branch: main
notifications:
  email: false